### ISSUE TITLE
Parallel VecEnv not working

### ISSUE THREAD

**Issue by sampreet-arthi** [SforAiDl/genrl#172]
```
env = venv("Pendulum-v0", n_envs=5, parallel=True)
agent = DQN("mlp", env)
trainer = OffPolicyTrainer(agent, env)
trainer.train()
trainer.evaluate()
```

This code is not working (not in the current master nor in #128 ). Returns several runtime errors.

![image](https://user-images.githubusercontent.com/12513634/84651884-476b7a00-af28-11ea-866b-89060c33822d.png)

**Comment by Sharad24** [comment]
Is this on Colab?

**Comment by Zeus3101** [comment]
No, locally on VS Code

**Comment by Zeus3101** [comment]
It doesn't work with the `deep.py` parser either

**Comment by Sharad24** [comment]
@Het-Shah 

Yeah deep.py is just for ease

**Comment by Het-Shah** [comment]
Can you give the full trace of the errors that you are getting?

**Comment by Zeus3101** [comment]
> Can you give the full trace of the errors that you are getting?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\sampr\.conda\envs\rl\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\sampr\.conda\envs\rl\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\sampr\.conda\envs\rl\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Files\Reinforcement Learning\Repos\GenRL\genrl\tester.py", line 5, in <module>
    env = VectorEnv("CartPole-v0", n_envs=5, parallel=True)
  File "c:\Files\Reinforcement Learning\Repos\GenRL\genrl\genrl\environments\suite.py", line 49, in VectorEnv
    venv = SubProcessVecEnv(envs, n_envs)
  File "c:\Files\Reinforcement Learning\Repos\GenRL\genrl\genrl\environments\vec_env\vector_envs.py", line 226, in __init__
    process.start()
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sampr\.conda\envs\rl\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

This repeats 5 times (cos I used n_envs=5)

**Comment by Zeus3101** [comment]
```
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
<ipython-input-16-cbd87917f2fe> in <module>()
      3 trainer = OffPolicyTrainer(agent, env, log_interval=200, epochs=1)
      4 trainer.train()
----> 5 trainer.evaluate()

5 frames
/content/genrl/genrl/deep/common/trainer.py in evaluate(self)
    118         ep, ep_r = 0, np.zeros(self.env.n_envs)
    119         ep_rews = []
--> 120         state = self.env.reset()
    121         while True:
    122             if self.off_policy:

/content/genrl/genrl/environments/vec_env/vec_normalize.py in reset(self)
    108         """
    109         self.returns = np.zeros((self.n_envs,), dtype=np.float32)
--> 110         states = self.venv.reset()
    111         return self._normalize(self.obs_rms, self.clip_obs, states)
    112 

/content/genrl/genrl/environments/vec_env/vector_envs.py in reset(self)
    252         """
    253         for parent_conn in self.parent_conns:
--> 254             parent_conn.send(("reset", None))
    255 
    256         obs = [parent_conn.recv() for parent_conn in self.parent_conns]

/usr/lib/python3.6/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(_ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/usr/lib/python3.6/multiprocessing/connection.py in _send_bytes(self, buf)
    402             # Also note we want to avoid sending a 0-length buffer separately,
    403             # to avoid "broken pipe" errors if the other end closed the pipe.
--> 404             self._send(header + buf)
    405 
    406     def _recv_bytes(self, maxsize=None):

/usr/lib/python3.6/multiprocessing/connection.py in _send(self, buf, write)
    366         remaining = len(buf)
    367         while True:
--> 368             n = write(self._handle, buf)
    369             remaining -= n
    370             if remaining == 0:

BrokenPipeError: [Errno 32] Broken pipe
```

This is on Colab

**Comment by Het-Shah** [comment]
aah pipe errors fml

**Comment by Sharad24** [comment]
Is this still not working?

**Comment by sampreet-arthi** [comment]
Nope
