### ISSUE TITLE
AttributeError: module 'tensorboard.lazy' has no attribute 'lazy_load'

### ISSUE THREAD

**Issue by nbro** [SforAiDl/genrl#387]
I'm trying to execute this simple code

```
import gym

from genrl.agents import QLearning
from genrl.trainers import ClassicalTrainer

env = gym.make("FrozenLake-v0")

agent = QLearning(env)
trainer = ClassicalTrainer(agent, env, mode="dyna", model="tabular", n_episodes=10000)
episode_rewards = trainer.train()
trainer.plot(episode_rewards)
```

However, I am getting the error

> AttributeError: module 'tensorboard.lazy' has no attribute 'lazy_load'

with the stack trace

```
Traceback (most recent call last):
  File "/Users/nbro/Desktop/phd/code/rf_testing/example11.py", line 3, in <module>
    from genrl.agents import QLearning
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/genrl/agents/__init__.py", line 1, in <module>
    from genrl.agents.bandits.contextual.base import DCBAgent  # noqa
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/genrl/agents/bandits/contextual/base.py", line 5, in <module>
    from genrl.core import Bandit, BanditAgent
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/genrl/core/__init__.py", line 1, in <module>
    from genrl.core.actor_critic import MlpActorCritic, get_actor_critic_from_name  # noqa
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/genrl/core/actor_critic.py", line 10, in <module>
    from genrl.core.policies import MlpPolicy
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/genrl/core/policies.py", line 6, in <module>
    from genrl.utils import cnn, mlp
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/genrl/utils/__init__.py", line 10, in <module>
    from genrl.utils.logger import CSVLogger  # noqa
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/genrl/utils/logger.py", line 5, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorboard/summary/v1.py", line 24, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorboard/plugins/audio/summary.py", line 34, in <module>
    import tensorflow as tf
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorflow_core/_api/v1/compat/__init__.py", line 24, in <module>
    from tensorflow._api.v1.compat import v2
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorflow_core/_api/v1/compat/v2/__init__.py", line 322, in <module>
    from tensorboard.summary._tf import summary
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorboard/summary/_tf/summary/__init__.py", line 175, in <module>
    from tensorboard.summary.v2 import audio
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorboard/summary/v2.py", line 24, in <module>
    from tensorboard.plugins.audio.summary_v2 import audio
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorboard/plugins/audio/summary_v2.py", line 30, in <module>
    from tensorboard.compat import tf2 as tf
  File "/Users/nbro/.conda/envs/rf_testing/lib/python3.7/site-packages/tensorboard/compat/__init__.py", line 31, in <module>
    @_lazy.lazy_load('tensorboard.compat.tf')
AttributeError: module 'tensorboard.lazy' has no attribute 'lazy_load'

Process finished with exit code 1
```

I had installed this package with 

```
pip install genrl
```

And I remember there were some incompatibility issues. I am getting now the same error messages after having reinstalled `tensorflow-tensorboard` and `tensorboard`, as suggested in [this answer](https://stackoverflow.com/a/57619480/3924118).

```
genrl 0.0.2 requires certifi==2019.11.28, but you'll have certifi 2020.6.20 which is incompatible.
genrl 0.0.2 requires cloudpickle==1.3.0, but you'll have cloudpickle 1.6.0 which is incompatible.
genrl 0.0.2 requires gym==0.17.1, but you'll have gym 0.17.3 which is incompatible.
genrl 0.0.2 requires matplotlib==3.2.1, but you'll have matplotlib 3.3.2 which is incompatible.
genrl 0.0.2 requires numpy==1.18.2, but you'll have numpy 1.15.4 which is incompatible.
genrl 0.0.2 requires opencv-python==4.2.0.34, but you'll have opencv-python 4.4.0.46 which is incompatible.
genrl 0.0.2 requires pandas==1.0.4, but you'll have pandas 1.1.4 which is incompatible.
genrl 0.0.2 requires Pillow==7.1.0, but you'll have pillow 8.0.1 which is incompatible.
genrl 0.0.2 requires scipy==1.4.1, but you'll have scipy 1.5.3 which is incompatible.
genrl 0.0.2 requires six==1.14.0, but you'll have six 1.15.0 which is incompatible.
```

Doing 

```
pip install tensorflow-tensorboard==1.5.1
```

and then

```
pip install tensorboard==1.15.0
```

Actually, solved this issue `AttributeError: module 'tensorboard.lazy' has no attribute 'lazy_load'`, but I think you should be aware of it, and that people can encounter it, as I did, while using your package.

**Comment by sampreet-arthi** [comment]
Hey thanks for pointing this out! We were unaware of this issue. We'll try to fix this in our next release. 

Could you try installing the latest (unstable) build by doing `git clone` and then `python setup.py install`?
